Agregando las 'clausulas para invitar' a @leonel
colombia-dev/leonel pull request #57
Opened 2016-10-26 19:27 UTC by JosueDanielBust

2016-10-26 20:32 UTC, JosueDanielBust commented
Second pull request try to solve issue #36 with the comment of Yeiner

2016-10-26 21:04 UTC, JosueDanielBust commented
Third push corresponding to #39 issue

2016-10-27 01:25 UTC, buritica requested changes
Se ve bien, si le agregas pruebas le hago merge :P

2016-10-27 01:25 UTC, buritica commented on index.js
> +    '- Son falta de respuesta.',
Creo que esto esta mal redactado :P

2016-10-27 01:25 UTC, buritica commented on index.js
> +controller.hears(['clausulas', 'clausulas', 'clause', 'why'], ['direct_message', 'direct_mention'], (bot, message) => {
pruebas :D

2016-11-18 05:28 UTC, JosueDanielBust commented
@buritica I think that I need some help for make the tests, I search on docs for learn to do but I don't know where start or what I need really do 😣

2016-11-22 15:22 UTC, buritica commented
did you check the tests that are already there?


give it a try and I'll help you out

On Fri, Nov 18, 2016 at 00:28 Josue Daniel Bustamante <
notifications@github.com> wrote:

> @buritica <https://github.com/buritica> I think that I need some help for
> make the tests, I search on docs for learn to do but I don't know where
> start or what I need really do 😣
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/colombia-dev/leonel/pull/57#issuecomment-261452029>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAN7GMWKFKL644oUpRU0WMElYqE9ru24ks5q_TeSgaJpZM4Khkf2>
> .
>

2017-01-11 03:50 UTC, JosueDanielBust commented
@buritica what do you think about this test?

2017-03-06 02:06 UTC, buritica commented
hey @JosueDanielBust, thank you for sending this PR, unfortunately I'm going to close it for the following reasons:

- the "clausulas" are a good idea, but they are the wrong solution for a UX problem. What I've done instead is improve the messages people get when something goes wrong during the invitation process #83

- the baires command seemed like a good idea at the time. After some thought, I think it's best if col-dev stays away from an official message about any company, even if they have really bad practices.

- the `coqueto` command is meant to be an easter egg, so we'd rather not have it in the help menu.

Thanks again, I can tell you did some really good work and invested your time. I can also see it helped you learn how to test, which is not easy to do! I'm sorry it took so long to get to this PR, if you have any new ideas, let me know and maybe we can discuss them together before you put any time into them, I'd hate for you to feel like you've wasted your time!

2017-03-06 02:06 UTC, closed without merging